apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
      - name: ${name}
        image: ${dockerImage}
        imagePullPolicy: Always
        ports:
        - containerPort: ${port}
        =[extraPorts,
        - containerPort: $
        ]
        =[secrets,
        env:
        - name: $.envName
          valueFrom:
            secretKeyRef:
              name: $.secretName
              key: $.secretKey
        ]
      imagePullSecrets:
        - name: regcred

