apiVersion: v1
kind: Service
metadata:
  name: ${name}
  labels:
    app: ${appName}
spec:
  selector:
    app: ${appName}
  ports:
  - port: ${port}
    targetPort: ${targetPort}
    protocol: TCP
    name: port-main
  =[localDevExtraPorts,
  - port: $.localPort
    targetPort: $.port
    protocol: TCP
    name: port-$.localPort
    ]
  type: LoadBalancer